# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='boolean',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
